# Generated by Django 2.2.7 on 2019-11-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=9)),
                ('ddd', models.CharField(max_length=4)),
                ('email', models.CharField(max_length=100)),
                ('kind', models.IntegerField(default=0)),
            ],
        ),
    ]
