# Generated by Django 2.2.7 on 2019-11-25 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191125_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='kind',
        ),
    ]
