# Generated by Django 2.2.7 on 2019-11-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('description', models.TextField(max_length=400)),
                ('value', models.FloatField()),
            ],
        ),
    ]
