# Generated by Django 2.2.7 on 2019-11-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='type',
            field=models.CharField(choices=[('arm', 'Arm'), ('leg', 'Leg'), ('body', 'Body'), ('head', 'Head'), ('blaster', 'Blaster'), ('shield', 'Shield')], max_length=15),
        ),
    ]
