version: '3'

services:
  mysqldb:
    image: mysql
    container_name: 'db'
    volumes:
      - ./.data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'droid_market_db'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      DATABASE_HOST: 127.0.0.1
    ports:
      - "3306:3306"
  django:
    build: .
    container_name: 'api'
    restart: always
    command: ./docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mysqldb
volumes:
  data: