version: '3'

services:
  db:
    image: mariadb
    volumes:
      - ./.data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: droid_market_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 'root'
      DATABASE_HOST: 127.0.0.1
    ports:
      - "3306:3306"
    networks:
      - back-tier
  api:
    build: .
    entrypoint: ./docker-entrypoint.sh
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
    networks:
      - back-tier
volumes:
 data:
networks:
 back-tier:
   driver: bridge