# Generated by Django 2.2.7 on 2019-11-27 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20191127_0121'),
        ('pieces', '0003_auto_20191127_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('neighborhood', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('cep', models.CharField(max_length=9)),
                ('status', models.IntegerField(choices=[(0, 'Opened'), (1, 'Finnished')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='users.UserProfile')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='pieces.Piece')),
            ],
        ),
    ]
